<?php
$translate = $this->plugin('translate');
$item = $media->item();
$this->headLink()->appendStylesheet($this->assetUrl('css/resource-page-blocks.css', 'Omeka'));
$this->htmlElement('body')->appendAttribute('class', 'media resource show'); 
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
?>

<?php echo $this->pageTitle($media->displayTitle(null, $valueLang), 1); ?>
<h2><?php echo $translate('Media'); ?></h2>
<?php $this->trigger('view.show.before'); ?>
<p class="media-parent-item">
    <?php echo sprintf($translate('Part of %s'), $item->link($item->displayTitle(null, $valueLang))); ?>
</p>
<?php echo $this->resourcePageBlocks($media)->getBlocks(); ?>
<?php $this->trigger('view.show.after'); ?>