<button id="section-sidebar-modal-close" class="close-button" aria-label="<?php echo $this->escapeHtml($this->translate('Close')); ?>" aria-labelledby="section-sidebar-modal-close section-sidebar" type="button">
  <span aria-hidden="true" class="close-glyph"></span>
</button>
<div class="sr-only" id="facet-modal-description">
    This is a dialog window which overlays the main content of the page. The modal begins with a fieldset called <?php echo $category->name(); ?>. Pressing the Close Modal button at the top right of the modal will close the modal and bring you back to where you were on the page.
</div>
<?php echo $this->hyperlink($this->translate('Back'), [], ['id' => 'categories-return', 'class' => 'button']); ?>
<fieldset class="facets-container">
    <legend><?php echo $category->name(); ?></legend>
    <?php
    $categoryOptions = [
        'value_facet_mode' => $category->valueFacetMode(),
    ];
    $helperText = $category->helperText();
    $helperTextButtonLabel = $category->helperTextButtonLabel();
    if ('' === trim($helperTextButtonLabel)) {
        $helperTextButtonLabel = $this->translate('Instructions');
    }
    ?>
    <?php if ($helperText): ?>
      <div class="instructions-wrapper accordion" id="instructionsAccordion">
        <div class="accordion-item">
          <div class="accordion-header">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#instructionsText" aria-expanded="true" aria-controls="instructionsText">
              <?php echo $this->escapeHtml($helperTextButtonLabel); ?>
            </button>
          </div>
          <div id="instructionsText" class="accordion-collapse collapse show" data-bs-parent="#instructionsAccordion">
            <div class="accordion-body">
              <?php echo $category->helperText(); ?>
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>
    <div id="facets"
        data-category-id="<?php echo $this->escapeHtml($category->id()); ?>"
        data-category-options="<?php echo $this->escapeHtml(json_encode($categoryOptions)); ?>">
        <?php foreach ($category->facets() as $facet): ?>
        <?php if ($this->facetedBrowse()->facetIsKnown($facet)): ?>
        <fieldset class="facet"
            data-facet-id="<?php echo $this->escapeHtml($facet->id()); ?>"
            data-facet-type="<?php echo $this->escapeHtml($facet->type()); ?>"
            data-facet-data="<?php echo $this->escapeHtml(json_encode($facet->data())); ?>">
            <legend><?php echo $facet->name(); ?></legend>
              <?php if ($facet->type() == "full_text"): ?>
                <label>
                  <span class="sr-only"><?php echo $facet->name(); ?></span>
                  <?php echo $this->facetedBrowse()->renderFacet($facet); ?>
                </label>
              <?php else: ?>
                <?php echo $this->facetedBrowse()->renderFacet($facet); ?>
              <?php endif; ?>
        </fieldset>
        <?php endif; ?>
        <?php endforeach; ?>
    </div>
</fieldset>