[info]
name = "Nebraskaland"
version = "1.0"
author = "Center for Digital Research in the Humanities"
description = "Omeka S theme designed for the Nebraskaland Digital Archive."
; theme_link = "https://github.com/cdrh/theme_nebraskaland"
author_link = "https://cdrh.unl.edu/"
omeka_version_constraint = "^4.1.0"

[config]

block_templates.asset.random-with-overlay = "Random asset with caption overlay"

element_groups.global = "Global Settings"
element_groups.top_menu = "Top Menu Links"
element_groups.footer_content = "Footer Content"
element_groups.home_images = "Homepage Images (Random)"

elements.nav_depth.name = "nav_depth"
elements.nav_depth.attributes.id = "nav_depth"
elements.nav_depth.type = "Number"
elements.nav_depth.options.label = "Top Navigation Depth"
elements.nav_depth.options.info = "Maximum number of levels to show in the site's top navigation bar. Set to 0 to show all levels."
elements.nav_depth.attributes.min = 0
elements.nav_depth.attributes.value = 0

elements.logo.name = "logo"
elements.logo.type = "Omeka\Form\Element\Asset"
elements.logo.options.label = "Logo"

elements.banner.name = "banner"
elements.banner.type = "Omeka\Form\Element\Asset"
elements.banner.options.label = "Banner"
elements.banner.options.info = "A large image at the top of the page"

elements.browse_body_truncation.name = "browse_body_truncation"
elements.browse_body_truncation.type = "Laminas\Form\Element\Select"
elements.browse_body_truncation.options.label = "Truncate Body Property"
elements.browse_body_truncation.options.info = "How to handle long values for the body property of each resource on the browse page."
elements.browse_body_truncation.options.value_options.full = "Show full value"
elements.browse_body_truncation.options.value_options.fade = "Show 4 lines and fade out"
elements.browse_body_truncation.options.value_options.ellipsis = "Show 4 lines and clip with an ellipsis"

elements.menu_link_1_text.name = "menu_link_1_text"
elements.menu_link_1_text.type = "Text"
elements.menu_link_1_text.options.label = "Link 1 Text"
elements.menu_link_1_text.options.info = "Text for 1st link that appears in the menu at the very top of the page."
elements.menu_link_1_text.options.element_group = "top_menu"

elements.menu_link_1.name = "menu_link_1"
elements.menu_link_1.type = "Laminas\Form\Element\Url"
elements.menu_link_1.options.label = "Link 1 URL"
elements.menu_link_1.options.info = "Text for 1st link that appears in the menu at the very top of the page."
elements.menu_link_1.options.element_group = "top_menu"

elements.menu_link_2_text.name = "menu_link_2_text"
elements.menu_link_2_text.type = "Text"
elements.menu_link_2_text.options.label = "Link 2 Text"
elements.menu_link_2_text.options.info = "2nd link that appears in the menu at the very top of the page."
elements.menu_link_2_text.options.element_group = "top_menu"

elements.menu_link_2.name = "menu_link_2"
elements.menu_link_2.type = "Laminas\Form\Element\Url"
elements.menu_link_2.options.label = "Link 2 URL"
elements.menu_link_2.options.info = "Text for 2nd link that appears in the menu at the very top of the page."
elements.menu_link_2.options.element_group = "top_menu"

elements.menu_link_3_text.name = "menu_link_3_text"
elements.menu_link_3_text.type = "Text"
elements.menu_link_3_text.options.label = "Link 3 Text"
elements.menu_link_3_text.options.info = "3rd link that appears in the menu at the very top of the page."
elements.menu_link_3_text.options.element_group = "top_menu"

elements.menu_link_3.name = "menu_link_3"
elements.menu_link_3.type = "Laminas\Form\Element\Url"
elements.menu_link_3.options.label = "Link 3 URL"
elements.menu_link_3.options.info = "Text for 3rd link that appears in the menu at the very top of the page."
elements.menu_link_3.options.element_group = "top_menu"

elements.menu_link_4_text.name = "menu_link_4_text"
elements.menu_link_4_text.type = "Text"
elements.menu_link_4_text.options.label = "Link 4 Text"
elements.menu_link_4_text.options.info = "4th link that appears in the menu at the very top of the page."
elements.menu_link_4_text.options.element_group = "top_menu"

elements.menu_link_4.name = "menu_link_4"
elements.menu_link_4.type = "Laminas\Form\Element\Url"
elements.menu_link_4.options.label = "Link 4 URL"
elements.menu_link_4.options.info = "Text for 4th link that appears in the menu at the very top of the page."
elements.menu_link_4.options.element_group = "top_menu"

elements.menu_link_5_text.name = "menu_link_5_text"
elements.menu_link_5_text.type = "Text"
elements.menu_link_5_text.options.label = "Link 5 Text"
elements.menu_link_5_text.options.info = "5th link that appears in the menu at the very top of the page."
elements.menu_link_5_text.options.element_group = "top_menu"

elements.menu_link_5.name = "menu_link_5"
elements.menu_link_5.type = "Laminas\Form\Element\Url"
elements.menu_link_5.options.label = "Link 5 URL"
elements.menu_link_5.options.info = "Text for 5th link that appears in the menu at the very top of the page."
elements.menu_link_5.options.element_group = "top_menu"

elements.footer.name = "footer"
elements.footer.attributes.id = "footer"
elements.footer.type = "Omeka\Form\Element\HtmlTextarea"
elements.footer.options.label = "Footer Content"
elements.footer.options.info = "HTML content that appears in the footer"
elements.footer.attributes.value = ""
elements.footer.options.element_group = "footer_content"

elements.logo_1.name = "logo_1"
elements.logo_1.type = "Omeka\Form\Element\Asset"
elements.logo_1.options.label = "Footer Logo 1"
elements.logo_1.options.info = "1st logo that appears in the footer"
elements.logo_1.options.element_group = "footer_content"

elements.logo_1_link.name = "logo_1_link"
elements.logo_1_link.type = "Laminas\Form\Element\Url"
elements.logo_1_link.options.label = "Footer Logo 1 Link"
elements.logo_1_link.options.info = "Use this to link Footer Logo 1 to any URL, internal or external (include the full URL starting with https://)"
elements.logo_1_link.options.element_group = "footer_content"

elements.logo_2.name = "logo_2"
elements.logo_2.type = "Omeka\Form\Element\Asset"
elements.logo_2.options.label = "Footer Logo 2 Image"
elements.logo_2.options.info = "2nd logo that appears in the footer"
elements.logo_2.options.element_group = "footer_content"

elements.logo_2_link.name = "logo_2_link"
elements.logo_2_link.type = "Laminas\Form\Element\Url"
elements.logo_2_link.options.label = "Footer Logo 2 Link"
elements.logo_2_link.options.info = "Use this to link Footer Logo 2 to any URL, internal or external (include the full URL starting with https://)"
elements.logo_2_link.options.element_group = "footer_content"

elements.logo_3.name = "logo_3"
elements.logo_3.type = "Omeka\Form\Element\Asset"
elements.logo_3.options.label = "Footer Logo 3 Image"
elements.logo_3.options.info = "3rd logo that appears in the footer"
elements.logo_3.options.element_group = "footer_content"

elements.logo_3_link.name = "logo_3_link"
elements.logo_3_link.type = "Laminas\Form\Element\Url"
elements.logo_3_link.options.label = "Footer Logo 3 Link"
elements.logo_3_link.options.info = "Use this to link Footer Logo 3 to any URL, internal or external (include the full URL starting with https://)"
elements.logo_3_link.options.element_group = "footer_content"

elements.logo_4.name = "logo_4"
elements.logo_4.type = "Omeka\Form\Element\Asset"
elements.logo_4.options.label = "Footer Logo 4 Image"
elements.logo_4.options.info = "4th logo that appears in the footer"
elements.logo_4.options.element_group = "footer_content"

elements.logo_4_link.name = "logo_4_link"
elements.logo_4_link.type = "Laminas\Form\Element\Url"
elements.logo_4_link.options.label = "Footer Logo 4 Link"
elements.logo_4_link.options.info = "Use this to link Footer Logo 4 to any URL, internal or external (include the full URL starting with https://)"
elements.logo_4_link.options.element_group = "footer_content"

elements.logo_5.name = "logo_5"
elements.logo_5.type = "Omeka\Form\Element\Asset"
elements.logo_5.options.label = "Footer Logo 5 Image"
elements.logo_5.options.info = "5th logo that appears in the footer"
elements.logo_5.options.element_group = "footer_content"

elements.logo_5_link.name = "logo_5_link"
elements.logo_5_link.type = "Laminas\Form\Element\Url"
elements.logo_5_link.options.label = "Footer Logo 5 Link"
elements.logo_5_link.options.info = "Use this to link Footer Logo 5 to any URL, internal or external (include the full URL starting with https://)"
elements.logo_5_link.options.element_group = "footer_content"

elements.home_rand.name = "home_rand"
elements.home_rand.type = "Laminas\Form\Element\Checkbox"
elements.home_rand.options.label = "Randomize Homepage Image"
elements.home_rand.options.info = "Check this box to display a banner on the homepage that randomly cycles through the images selected below."
elements.home_rand.options.element_group = "home_images"

elements.home_image_1.name = "home_image_1"
elements.home_image_1.type = "Omeka\Form\Element\Asset"
elements.home_image_1.options.label = "Home Image 1"
elements.home_image_1.options.info = "On load, the homepage will randomly choose one of the images in this section to display."
elements.home_image_1.options.element_group = "home_images"

elements.home_image_2.name = "home_image_2"
elements.home_image_2.type = "Omeka\Form\Element\Asset"
elements.home_image_2.options.label = "Home Image 2"
elements.home_image_2.options.info = "On load, the homepage will randomly choose one of the images in this section to display."
elements.home_image_2.options.element_group = "home_images"

elements.home_image_3.name = "home_image_3"
elements.home_image_3.type = "Omeka\Form\Element\Asset"
elements.home_image_3.options.label = "Home Image 3"
elements.home_image_3.options.info = "On load, the homepage will randomly choose one of the images in this section to display."
elements.home_image_3.options.element_group = "home_images"

elements.home_image_4.name = "home_image_4"
elements.home_image_4.type = "Omeka\Form\Element\Asset"
elements.home_image_4.options.label = "Home Image 4"
elements.home_image_4.options.info = "On load, the homepage will randomly choose one of the images in this section to display."
elements.home_image_4.options.element_group = "home_images"

elements.home_image_5.name = "home_image_5"
elements.home_image_5.type = "Omeka\Form\Element\Asset"
elements.home_image_5.options.label = "Home Image 5"
elements.home_image_5.options.info = "On load, the homepage will randomly choose one of the images in this section to display."
elements.home_image_5.options.element_group = "home_images"

elements.home_image_6.name = "home_image_6"
elements.home_image_6.type = "Omeka\Form\Element\Asset"
elements.home_image_6.options.label = "Home Image 6"
elements.home_image_6.options.info = "On load, the homepage will randomly choose one of the images in this section to display."
elements.home_image_6.options.element_group = "home_images"


resource_page_regions.items.main = "Main"
resource_page_regions.item_sets.main = "Main"
resource_page_regions.media.main = "Main"

resource_page_blocks.items.main[] = "mediaEmbeds"
resource_page_blocks.items.main[] = "values"
resource_page_blocks.items.main[] = "itemSets"
resource_page_blocks.items.main[] = "sitePages"
resource_page_blocks.items.main[] = "mediaList"
resource_page_blocks.items.main[] = "linkedResources"
resource_page_blocks.item_sets.main[] = "values"
resource_page_blocks.media.main[] = "mediaRender"
resource_page_blocks.media.main[] = "values"

page_templates.homepage = "Homepage with random image"