<?php $escape = $this->plugin('escapeHtml'); ?>
<?php $attachmentCount = count($attachments); ?>
<?php $randomAttachment = rand(1, $attachmentCount); ?>

<div class="assets display-attachment-<?php echo $randomAttachment; ?>">
  <?php 
  $i = 1;
  foreach ($attachments as $attachment): ?>
    <?php $asset = $attachment['asset']; ?>
    <?php $assetImage = ($asset) ? $this->thumbnail($asset, 'square', ['class' => 'card-image']) : ''; ?>
    <div class="asset attachment-<?php echo $i++; ?> random-background-image">
      <div class="random-image-wrapper">
        <img src="<?php echo $asset->assetUrl(); ?>" alt="<?php echo $asset->altText(); ?>" />
        <?php if ($attachment['caption'] !== ''): ?>
          <div class="caption-wrapper">
            <div class="caption">
              <?php echo $attachment['caption']; ?>
            </div>
          </div>
        <?php endif; ?>
      </div>
    </div>
  <?php endforeach; ?>
</div>
