<?php if ($this->themeSetting('logo_1')): ?>
  <?php if ($this->themeSetting('logo_1_link')): ?><a href="<?php echo $this->themeSetting('logo_1_link'); ?>"><?php endif; ?>
    <img src="<?php echo $this->themeSettingAssetUrl('logo_1'); ?>" alt="<?php echo $this->themeSettingAsset('logo_1')->altText(); ?>" />
  <?php if ($this->themeSetting('logo_1_link')): ?></a><?php endif; ?>
<?php endif; ?>

<?php if ($this->themeSetting('logo_2')): ?>
  <?php if ($this->themeSetting('logo_2_link')): ?><a href="<?php echo $this->themeSetting('logo_2_link'); ?>"><?php endif; ?>
    <img src="<?php echo $this->themeSettingAssetUrl('logo_2'); ?>" alt="<?php echo $this->themeSettingAsset('logo_2')->altText(); ?>" />
  <?php if ($this->themeSetting('logo_2_link')): ?></a><?php endif; ?>
<?php endif; ?>

<?php if ($this->themeSetting('logo_3')): ?>
  <?php if ($this->themeSetting('logo_3_link')): ?><a href="<?php echo $this->themeSetting('logo_3_link'); ?>"><?php endif; ?>
    <img src="<?php echo $this->themeSettingAssetUrl('logo_3'); ?>" alt="<?php echo $this->themeSettingAsset('logo_3')->altText(); ?>" />
  <?php if ($this->themeSetting('logo_3_link')): ?></a><?php endif; ?>
<?php endif; ?>

<?php if ($this->themeSetting('logo_4')): ?>
  <?php if ($this->themeSetting('logo_4_link')): ?><a href="<?php echo $this->themeSetting('logo_4_link'); ?>"><?php endif; ?>
    <img src="<?php echo $this->themeSettingAssetUrl('logo_4'); ?>" alt="<?php echo $this->themeSettingAsset('logo_4')->altText(); ?>" />
  <?php if ($this->themeSetting('logo_4_link')): ?></a><?php endif; ?>
<?php endif; ?>

<?php if ($this->themeSetting('logo_5')): ?>
  <?php if ($this->themeSetting('logo_5_link')): ?><a href="<?php echo $this->themeSetting('logo_5_link'); ?>"><?php endif; ?>
    <img src="<?php echo $this->themeSettingAssetUrl('logo_5'); ?>" alt="<?php echo $this->themeSettingAsset('logo_5')->altText(); ?>" />
  <?php if ($this->themeSetting('logo_5_link')): ?></a><?php endif; ?>
<?php endif; ?>