<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headLink()->prependStylesheet('https://use.typekit.net/kzr8rev.css');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Source+Code+Pro%7CLato:400,400italic,700,700italic');
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' | ');
$this->headLink()->appendStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
// $this->headLink()->appendStylesheet($this->assetUrl('css/style.css', 'Omeka'));
$this->headScript()->appendFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->jsTranslate();

// Bootstrap CSS and Javascript links
$this->headLink()->appendStylesheet($this->assetUrl('vendor/bootstrap/css/bootstrap-reboot.css'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/bootstrap/css/bootstrap.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/bootstrap/css/bootstrap-grid.min.css'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/bootstrap/css/bootstrap-reboot.min.css'));
$this->headScript()->appendFile($this->assetUrl('vendor/bootstrap/js/bootstrap.bundle.js'));

// Fancybox
$this->headLink()->appendStylesheet($this->assetUrl('vendor/fancybox/css/fancybox.min.css'));
$this->headScript()->appendFile($this->assetUrl('vendor/fancybox/js/fancybox.min.js'));
$this->headScript()->appendFile($this->assetUrl('vendor/fancybox/js/item_gallery_lightbox.js'));

// Theme CSS
$this->headLink()->appendStylesheet($this->assetUrl('css/style.css'));
// Theme JS 
// $this->headScript()->appendFile($this->assetUrl('js/nebraskaland.js'));

$this->trigger('view.layout');
$userBar = $this->userBar();

// Subnav maybe 

$nav = $site->publicNav();
$activePage = $nav->findActive($nav->getContainer());
$showPagePagination = $this->siteSetting('show_page_pagination', false);

?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html')->setAttribute('lang', $this->lang()); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->partial('common/header/favicon'); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <?php if ($this->themeSettingAsset('banner')): ?>
          <style type="text/css">
            .banner { 
              background-image: url(<?php echo $this->themeSettingAssetUrl('banner'); ?>);
            }
          </style>
        <?php endif; ?>
    </head>
    <?php echo $this->htmlElement('body')->appendAttribute('id', 'body-wrapper'); ?>
        <header>
        <div href="#content" class="sr-only sr-only-focusable">
          Skip to main content
        </div>
          <?php echo $userBar; ?>
          <?php echo $this->partial('common/header/top-menu'); ?>
          <?php echo $this->partial('common/header/site-title'); ?>
            <div class="main-menu navbar navbar-expand-sm">
              <button class="navbar-toggler m-2 ms-auto" type="button" data-bs-toggle="collapse" data-bs-target="#mainMenuContainer" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse justify-content-center" id="mainMenuContainer">
                  <nav id="mainMenu" aria-label="Main Menu">
                    <?php
                      echo $site->publicNav()->menu()->renderMenu(null, [
                          'maxDepth' => $this->themeSetting('nav_depth') - 1,
                          'id' => 'navbar-nav'
                      ]);
                    ?>
                  </nav>
              </div>
            </div>
          </div>
        </header>
        <main id="content">
            <div class="container">
              <?php echo $this->messages(); ?>
              <?php // if ($this->isHomePage() == 'true'): ?>
                <!-- Home page! -->
                <?php // endif; ?>
              <?php echo $this->content; ?>
            </div>
        </main>
        <footer id="footer">
          <div class="container">
            <?php if ($this->themeSetting('footer')): ?>
              <div class="footer-text">
                <?php echo $this->themeSetting('footer'); ?>
              </div>
            <?php endif; ?>
            <?php if ($this->themeSettingAsset('logo_1')): ?>
              <div class="footer-logos">
                <?php echo $this->partial('common/footer/logos'); ?>
              </div>
            <?php endif; ?>
          </div>
        </footer>
    </body>
</html>